name 'heppuppet-vosupport'
version '0.0.1'

author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
project_page 'http://www.eu-emi.eu/'
summary 'VO default definitions and setup tools'
description 'This modules provides classes and definitions required to setup a list of supported VOs.'
dependency 'puppetlabs/stdlib', '~4'
dependency 'ripienaar/concat', '>=0.2.0'
